services:
  db:
    image: mysql:lts-oraclelinux9
    container_name: ${DATABASE_NAME}
    restart: "unless-stopped"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
    volumes:
      - chatapp_db-data:/var/lib/mysql

  db_admin:
    image: phpmyadmin
    container_name: chatapp_db_admin
    ports:
      - 8080:80
    restart: "unless-stopped"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - chatapp_db_admin:/var/lib/mysql

  api:
    build: ./server
    image: ${DOCKER_USERNAME}/chatapp-backend
    container_name: chatapp_backend
    ports:
      - 5000:5000
      - 5555:5555
    env_file:
      - ./server/.docker.env
    volumes:
      - ./server:/backend
      - /backend/node_modules
    restart: "unless-stopped"
    depends_on:
      - db

  web:
    build: ./client
    image: ${DOCKER_USERNAME}/chatapp-frontend
    container_name: chatapp_frontend
    ports:
      - 3000:3000
    env_file:
      - ./client/.docker.env
    volumes:
      - ./client:/frontend
      - /frontend/node_modules
    restart: "unless-stopped"
    depends_on:
      - api

volumes:
  chatapp_db-data:
  chatapp_db_admin:
